test: add `None` arguments to `typing.Generator`
Python versions older than 3.13 raises:
`TypeError: Too few arguments for typing.Generator; actual 1, expected 3`

https://docs.python.org/3/library/typing.html#typing.Generator:
`Changed in version 3.13: Default values for the send and return types were added.`

Signed-off-by: Daniel Skinstad Drabitzius <daniel.drabitzius@northern.tech>